In [1]:
import numpy as np

NumPy Array
El array es el principal objeto de la librería. Representa datos de manera estructurada y se puede acceder a ellos a traves del indexado, a un dato específico o un grupo de muchos datos específicos.

In [2]:
list = [1,2,3,4,5,6,7,8,9,10]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
arr = np.array(list)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
type(arr)

numpy.ndarray

In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

El indexado nos permite acceder a los elementos de los array y matrices
Los elementos se emepiezan a contar desde 0.

In [7]:
arr[2]

3

Es posible operar directamente con los elementos. 

In [8]:
arr[0] + arr[5]

7

En el caso de las matrices al indezar una posición se regresa el array de dicha posición.

In [9]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Para seleccionar un solo elemento de la matriz se especifica la posición del elemento separada por comas.

In [10]:
matrix[1,1]

5

In [11]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

El slicing nos permite extraer varios datos, tiene un comienzo y un final.
En este ejemplo se está extrayendo datos desde la posición 1 hasta la 5. [1:6].

In [12]:
arr[0:3]

array([1, 2, 3])

In [13]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

En cambio si no se le da una posción de End se regresan todos los elementos hasta el final del array.

In [14]:
arr[6:]

array([ 7,  8,  9, 10])

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

También se puede trabajar por pasos.
En este ejemplo de 3 en 3.
Regresa la posición 0, 0 + 3, 3 + 3 y como no hay posición 6 + 3, no se regrese nada.

In [16]:
arr[::3]

array([ 1,  4,  7, 10])

Cuando se le asigna un valor negativo se regresan los valores comenzando desde la última posición del array.

In [17]:
arr[-3:]

array([ 8,  9, 10])

In [18]:
arr[-1]

10

Para el caso de las matrices sucede algo similar.
Para acceder a los valores a nivel de filas.

In [19]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Para acceder a los valores a nivel de filas y columnas.

In [20]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])

*PRACTICA* 

Realizar y ver basicamente que onda que rollo con una matriz de mas de 3 dimensiones (aunque una matriz de 3 o mas dimensiones ya se considera un tensor)

A la matriz la llamaremos TensorMatrix y le daremos valores del 1 al 18

In [21]:
TensorMatrix = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                [[10,11,12],[13,14,15],[16,17,18]]])
TensorMatrix

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [22]:
TensorMatrix[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
TensorMatrix[1,0]

array([10, 11, 12])

*CóMO HACER SLICING?*

Es de la misma manera que en una matriz de 2 dimensiones, simplemente le ponemos un paramétro más

In [24]:
TensorMatrix[0,:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [25]:
TensorMatrix[0,1,2]

6

a hola
